app/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # Регистрация пользователя
    path('register/', views.user_register, name='register'),

    # Просмотр профиля
    path('profile/<str:slug>/',
         views.ProfileDetailView.as_view(),
         name='profile_detail'),

    # Редактирование профиля
    path('profile/<str:slug>/edit',
         views.ProfileUpdateView.as_view(),
         name='profile_edit'),

    # Взаимодействие с курсами
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('course/<pk>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail'),
    path('course/<pk>/<module_id>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

import account.forms

urlpatterns = [
    path('admin/', admin.site.urls),

    # core
    path('', include('core.urls', namespace='core')),

    # account
    path('account/', include('account.urls')),
    # Аутентификация и авторизация
    # Кастомный вход
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=account.forms.LoginForm
         ),
         name='login'),
    # Встроенные представления аутентификации
    path('', include('django.contrib.auth.urls')),

    # education
    path('education/', include('education.urls')),

    # faq
    path('faq/', include('faq.urls')),

    # chat
    path('chat/', include('chat.urls')),
]

# Раздаем статические файлы через джанго для разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/core/urls.py
from . import views

from django.urls import path

app_name = 'core'

urlpatterns = [
    # Домашняя страница
    path('', views.home_page, name='home'),
]

app/education/urls.py
from django.urls import path
from . import views

app_name = 'education'

urlpatterns = [
    # Курсы
    # Менеджмент курсами
    path('my_courses/',
         views.ManageCourseListView.as_view(),
         name='manage_course_list'),
    path('create/',
         views.CourseCreateView.as_view(),
         name='course_create'),
    path('<pk>/edit/',
         views.CourseUpdateView.as_view(),
         name='course_edit'),
    path('<pk>/delete/',
         views.CourseDeleteView.as_view(),
         name='course_delete'),
    # Просмотр курсов
    path('',
         views.CourseListView.as_view(),
         name='course_list'),
    path('subject/<slug:subject>/',
         views.CourseListView.as_view(),
         name='course_list_subject'),
    path('<slug:slug>/',
         views.CourseDetailView.as_view(),
         name='course_detail'),

    # Модули
    path('<int:course_id>/module/',
         views.CourseModuleUpdateView.as_view(),
         name='course_module_update'),
    path('module/<int:module_id>/',
         views.ModuleContentListView.as_view(),
         name='module_content_list'),

    # Контент
    path('module/<int:module_id>/content/<str:model_name>/create/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_create'),
    path('module/<int:module_id>/content/<str:model_name>/<id>/',
         views.ContentCreateUpdateView.as_view(),
         name='module_content_update'),
    path('content/<int:id>/delete/',
         views.ContentDeleteView.as_view(),
         name='module_content_delete'),

    # Порядок (Order)
    path('module/order/',
         views.ModuleOrderView.as_view(),
         name='module_order'),
    path('content/order/',
         views.ContentOrderView.as_view(),
         name='content_order'),
]

app/faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    # Статьи
    path('comments/', views.faq_list, name='faq_list'),

    # Детализация поста
    path('<int:year>/<int:month>/<int:day>/<slug:comm>/',
         views.faq_detail,
         name='comment_detail'),

    # Создать комментарий
    path('<int:post_id>/commentary/',
         views.faq_commentary, name='post_commentary')
]

app/core/views.py
from django.shortcuts import render


def home_page(request):
    return render(request, 'home.html')

app/core/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=PT+Sans:ital,wght@0,400;0,700;1,400&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/core.css' %}">
    <link rel="stylesheet" href="{% static 'css/account.css' %}">
    <link rel="stylesheet" href="{% static 'css/education.css' %}">
    <link rel="stylesheet" href="{% static 'css/faq.css' %}">
    <link rel="stylesheet" href="{% static 'css/chat.css' %}">

    {% comment %} <link rel="stylesheet" href="{% static 'fonts/font-awesome.min.css'%}"> {% endcomment %}

    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="wrapper">
        <div class="wrapper__header-content">

            <div class="topnav">
                <div class="container">
                    <div class="topnav__body">

                        <a href="/" class="topnav__logo">
                            <img src="{% static 'img/header_logo.png' %}" alt="TaskMetrics">
                        </a>

                        {% if request.user.is_authenticated %}


                            <div class="topnav__burger">
                                <span></span>
                            </div>

                            <nav class="topnav__menu">
                                <ul class="topnav__list">
                                    <li>
                                        <a href="{% url 'account:profile_detail' slug=request.user.profile.slug %}"  class="topnav__link">Профиль</a>
                                    </li>
                                    <li>
                                        <div class="topnav_educ_dropdown">
                                            <button class="topnav__link topnav_educ_dropdown__btn">Обучение
                                                <i></i>
                                            </button>
                                            <div class="topnav_educ_dropdown__content">
                                                <a href="{% url 'education:course_list' %}" class='topnav__link'>Все курсы</a>
                                                <a href="{% url 'education:manage_course_list' %}" class='topnav__link'>Управление курсами</a>
                                            </div> 
                                        </div>
                                    </li>
                                    <li>
                                        <a href="{% url 'faq:faq_list' %}" class="topnav__link">FAQ</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'logout' %}" class="topnav__link logout_logo fa-solid fa-person-through-window"></a>
                                    </li>
                                </ul>
                            </nav>

                        {% else %}
                            <div class="topnav__login_reg">
                                <ul class="topnav__welcome_list">
                                    <li>
                                        <a href="{% url 'login' %}" class="topnav__link login">Войти</a>
                                    </li>
                                    <li>
                                        <a href="{% url 'account:register' %}" class="topnav__link register">Регистрация</a>
                                    </li>
                                </ul>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>


            <div class="messages">
                {% if messages %}
                    <ul class="messages">
                        {% for message in messages %}
                            <li class="{{ message.tags }}">
                                {{ message|safe }}
                                <a href="#" class="close">x</a>
                            </li>
                        {% endfor %}
                    </ul>
                {% endif %}
            </div>

            <div class="content">
            <!-- Здесь располагается основное содержимое страницы -->
                {% block content %}
                {% endblock %}
            </div>


        </div>


        {% block footer %}
            <div class="wrapper__footer">
                <div class="footer">

                    <div class="footer__container">
                        <div class="footer__content">
                            <div class="footer__content__first-col">
                                <img src="{% static 'img/footer_logo.png' %}" alt="TaskMetrics">
                            </div>
                            <nav class="footer__content__second-col">
                                <div class="footer__content__second-col-left">
                                    <div class="footer__content__second-col-left-title">О приложении</div>
                                    <ul>
                                        <li class="footer__content-li">
                                            <a href="{% url 'core:home' %}">Информация</a>
                                        </li>
                                        <li class="footer__content-li">
                                            <a href="{% url 'faq:faq_list' %}">Справка</a>
                                        </li>
                                        <li class="footer__content-li">
                                            <a href="#">Пожелания</a>
                                        </li>
                                    </ul>
                                </div>
                                <div class="footer__content__second-col-right">
                                    <div class="footer__content__second-col-left-title">Полезные ссылки</div>
                                    <ul>
                                        <li class="footer__content-li">
                                            <a href="#">Confluence</a>
                                        </li>
                                        <li class="footer__content-li">
                                            <a href="#">JIRA</a>
                                        </li>
                                        <li class="footer__content-li">
                                            <a href="#">АСТП</a>
                                        </li>
                                        <li class="footer__content-li">
                                            <a href="#">Outlook</a>
                                        </li>
                                    </ul>
                                </div>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
        {% endblock %}


    </div>

    {% block include_js %}
    {% endblock %}

    <script>
        document.addEventListener('DOMContentLoaded', (event) => {
            // DOM-модель загружена
            {% block domready %}
            {% endblock %}
        })
    </script>

    <script src="{% static 'js/header_burger.js' %}"></script>
    <script src="{% static 'js/list_right-column.js' %}"></script>
    <script src="{% static 'js/add_commentary.js' %}"></script>
    <script src="https://kit.fontawesome.com/1000bd427f.js" crossorigin="anonymous"></script>

</body>
</html>

app/core/templates/home.html
{% extends 'base.html' %}

{% block title %}TaskMetrics{% endblock %}

{% block content %}
  <h1>Добро пожаловать в TaskMetrics</h1>
  <p>
    Мы стремимся предоставить вам уникальный опыт обучения и развития.
  </p>
  <p>
    Наш проект предлагает разнообразные курсы по различным темам, начиная от технологий и заканчивая творчеством.<br>
    У нас есть опытные преподаватели и интересные задания, чтобы сделать ваш образовательный путь увлекательным и полезным.
  </p>
  <p>
    Присоединяйтесь к нам и начните свое путешествие по новым знаниям и возможностям!
  </p>
  <p>
    Если у вас возникают вопросы, вы можете перейти в раздел <a href="{% url 'faq:faq_list' %}">FAQ (часто задаваемые вопросы)</a>
  </p>
    {% endblock %}