app/account/urls.py
from django.urls import path
from . import views

app_name = 'account'

urlpatterns = [
    # Регистрация пользователя
    path('register/', views.user_register, name='register'),

    # Просмотр профиля
    path('profile/<str:slug>/',
         views.ProfileDetailView.as_view(),
         name='profile_detail'),

    # Редактирование профиля
    path('profile/<str:slug>/edit',
         views.ProfileUpdateView.as_view(),
         name='profile_edit'),

    # Взаимодействие с курсами
    path('enroll-course/',
         views.StudentEnrollCourseView.as_view(),
         name='student_enroll_course'),
    path('courses/',
         views.StudentCourseListView.as_view(),
         name='student_course_list'),
    path('course/<pk>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail'),
    path('course/<pk>/<module_id>/',
         views.StudentCourseDetailView.as_view(),
         name='student_course_detail_module'),
]

app/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static

import account.forms

urlpatterns = [
    path('admin/', admin.site.urls),

    # core
    path('', include('core.urls', namespace='core')),

    # account
    path('account/', include('account.urls')),
    # Аутентификация и авторизация
    # Кастомный вход
    path('login/',
         auth_views.LoginView.as_view(
             template_name='registration/login.html',
             authentication_form=account.forms.LoginForm
         ),
         name='login'),
    # Встроенные представления аутентификации
    path('', include('django.contrib.auth.urls')),

    # education
    path('education/', include('education.urls')),

    # faq
    path('faq/', include('faq.urls')),

    # chat
    path('chat/', include('chat.urls')),
]

# Раздаем статические файлы через джанго для разработки
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

app/faq/urls.py
from django.urls import path
from . import views

app_name = 'faq'

urlpatterns = [
    # Статьи
    path('comments/', views.faq_list, name='faq_list'),

    # Детализация поста
    path('<int:year>/<int:month>/<int:day>/<slug:comm>/',
         views.faq_detail,
         name='comment_detail'),

    # Создать комментарий
    path('<int:post_id>/commentary/',
         views.faq_commentary, name='post_commentary')
]

app/account/models.py
from django.core.validators import FileExtensionValidator
from django.contrib.auth import get_user_model
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

User = get_user_model()


class Profile(models.Model):
    """
    Модель профиля пользователей
    """
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE
    )
    slug = models.SlugField(
        verbose_name='Слаг профиля',
        max_length=255,
        blank=True,
        unique=True
    )
    avatar = models.ImageField(
        verbose_name='Фотография профиля',
        upload_to='profile_avatars/%Y/%m/%d/',
        default='profile_avatars/default_profile_avatar.png',
        blank=True,
        validators=[FileExtensionValidator(allowed_extensions=('png', 'jpg', 'jpeg'))]
    )
    bio = models.TextField(
        max_length=500,
        blank=True,
        verbose_name='Информация о себе'
    )
    birth_date = models.DateField(
        blank=True,
        null=True,
        verbose_name='Дата рождения'
    )

    class Meta:
        """
        Сортировка, название таблицы в базе данных
        """
        db_table = 'account_users_profiles'
        ordering = ('user',)
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

    def save(self, *args, **kwargs):
        """
        Метод сохранения профиля для создания уникального url
        для входа в профиль
        """
        if not self.slug:
            self.slug = slugify(self.user.username)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        """
        Получение ссылки на профиль
        """
        return reverse('profile_detail', kwargs={'slug': self.slug})

    def __str__(self):
        return f'Профиль пользователя: {self.user.username}'

app/account/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.models import User
from .models import Profile
from education.models import Course


class LoginForm(AuthenticationForm):
    username = forms.CharField(
        label='Имя пользователя'
    )
    password = forms.CharField(
        widget=forms.PasswordInput,
        label='Пароль'
    )


class UserRegistrationForm(forms.ModelForm):
    username = forms.CharField(
        label='Ваш псевдоним (включая только буквы, цифры и @/./+/-/_):'
    )
    first_name = forms.CharField(label='Ваше имя')
    email = forms.EmailField(label='Email')
    password = forms.CharField(
        label='Пароль',
        widget=forms.PasswordInput
    )
    password2 = forms.CharField(
        label='Повторите пароль',
        widget=forms.PasswordInput
    )

    class Meta:
        model = User
        fields = ['username', 'first_name', 'email', 'password', 'password2']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Пароли не совпадают.')
        return cd['password2']

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError('Эта электронная почта уже используется.')
        return data

    def clean_username(self):
        data = self.cleaned_data['username']
        if User.objects.filter(username=data).exists():
            raise forms.ValidationError('Этот псевдоним уже используется.')
        return data


class UserUpdateForm(forms.ModelForm):
    """
    Форма изменения пользователя.
    """

    def clean_email(self):
        """
        Проверяет есть ли предоставляемый email в БД. Если есть, то райзит ошибку,
        иначе возвращает почту
        """
        email = self.cleaned_data['email']
        queryset = User.objects.filter(email=email).exclude(id=self.instance.id)
        if queryset.exists():
            raise forms.ValidationError('Эта электронная почта уже используется')
        return email

    class Meta:
        model = User
        fields = [
            'first_name',
            'last_name',
            'email'
        ]
        labels = {
            'first_name': 'Имя',
            'last_name': 'Фамилия',
            'email': 'Электронная почта',
        }


class ProfileUpdateForm(forms.ModelForm):
    birth_date = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}),
        label='Дата рождения',
        help_text='Введите вашу дату рождения'
    )

    delete_avatar = forms.BooleanField(
        required=False,
        initial=False,
        label='Удалить текущую фотографию',
        help_text='Отметьте, если хотите удалить текущую фотографию'
    )

    class Meta:
        model = Profile
        fields = [
            'birth_date',
            'avatar',
            'bio',
            'slug'
        ]
        labels = {
            'avatar': 'Фотография',
            'birth_date': 'Дата рождения',
            'bio': 'Информация о себе',
            'slug': 'Ссылка на профиль'
        }
        widgets = {
            'avatar': forms.FileInput(attrs={'class': 'form-control'}),
        }


class CourseEnrollForm(forms.Form):
    """
    Форма для зачисления студентов на курсы
    """
    course = forms.ModelChoiceField(
        queryset=Course.objects.all(),
        widget=forms.HiddenInput
    )

app/account/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from education.models import Course
from .forms import ProfileUpdateForm, CourseEnrollForm
from .models import Profile
from .services.services import service_create_user_registration_form, ServiceProfileUpdate


def user_register(request):
    """
    Регистрация пользователей
    """
    # Вызываем функцию для создания формы
    user_form, new_user = service_create_user_registration_form(request)

    # Если создаем нового пользователя:
    if new_user:
        return render(
            request,
            'registration/register_done.html',
            {'new_user': new_user}
        )

    # Если создаваемый пользователь уже существует:
    return render(
        request,
        'registration/register.html',
        {'user_form': user_form}
    )


class ProfileDetailView(DetailView):
    """
    Представление для просмотра профиля
    """
    model = Profile
    context_object_name = 'profile'
    template_name = 'profile/profile_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Страница пользователя: {self.object.user.username}'
        return context


class ProfileUpdateView(UpdateView):
    """
    Представление для редактирования профиля
    """
    model = Profile
    form_class = ProfileUpdateForm
    template_name = 'profile/profile_edit.html'

    def get_object(self, queryset=None):
        return self.request.user.profile

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = f'Редактирование профиля пользователя: {self.request.user.username}'
        context['user_form'] = ServiceProfileUpdate.get_user_edit_form(self.request)
        return context

    def form_valid(self, form):
        delete_avatar = form.cleaned_data.get('delete_avatar')
        if delete_avatar:
            profile = self.get_object()
            profile.avatar.delete()

        if ServiceProfileUpdate.save_profile_data(self.request, form):
            return super(ProfileUpdateView, self).form_valid(form)
        else:
            context = self.get_context_data()
            return self.render_to_response(context)

    def get_success_url(self):
        return ServiceProfileUpdate.get_success_url(self.object)


class StudentEnrollCourseView(LoginRequiredMixin, FormView):
    """
    Представление для обработки запросов на запись студента на курс.

    Атрибуты:
        course (Course): Курс, на который записывается студент.
        form_class (class): Класс формы, используемый для записи.

    Методы:
        form_valid(form): Обрабатывает случай, когда форма является валидной, и записывает студента на курс.
        get_success_url(): Возвращает URL для перенаправления после успешной записи.
    """
    course = None
    form_class = CourseEnrollForm

    def form_valid(self, form):
        """
        Обрабатывает случай, когда форма является валидной, и записывает студента на курс.

        Аргументы:
            form (CourseEnrollForm): Валидная форма записи.

        Возвращает:
            HttpResponse: Перенаправляет на URL успешной записи.
        """
        self.course = form.cleaned_data['course']
        self.course.students.add(self.request.user)
        return super().form_valid(form)

    def get_success_url(self):
        """
        Возвращает URL для перенаправления после успешной записи.

        Возвращает:
            str: URL успешной записи.
        """
        return reverse_lazy(
            'account:student_course_detail',
            args=[self.course.id]
        )


class StudentCourseListView(LoginRequiredMixin, ListView):
    """
    Представление списка курсов для студента.

    Attributes:
        model (Course): Модель курса.
        template_name (str): Имя шаблона для отображения списка курсов.

    Methods:
        get_queryset(): Получает и возвращает queryset курсов для текущего студента.
    """
    model = Course
    template_name = 'students/course/list.html'

    def get_queryset(self):
        """
        Получает и возвращает queryset курсов для текущего студента.

        Returns:
            QuerySet: queryset курсов для текущего студента.
        """
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])


class StudentCourseDetailView(DetailView):
    """
    Представление детальной информации о курсе для студента.

    Attributes:
        model (Course): Модель курса.
        template_name (str): Имя шаблона для отображения детальной информации.

    Methods:
        get_queryset(): Получает и возвращает queryset курсов для текущего студента.
        get_context_data(**kwargs): Получает и возвращает контекст для отображения детальной информации о курсе.
    """
    model = Course
    template_name = 'students/course/detail.html'

    def get_queryset(self):
        """
        Получает и возвращает queryset курсов для текущего студента.

        Returns:
            QuerySet: queryset курсов для текущего студента.
        """
        qs = super().get_queryset()
        return qs.filter(students__in=[self.request.user])

    def get_context_data(self, **kwargs):
        """
        Получает и возвращает контекст для отображения детальной информации о курсе.

        Args:
            **kwargs: Дополнительные аргументы.

        Returns:
            dict: Контекст для отображения детальной информации о курсе.
        """
        context = super().get_context_data(**kwargs)

        # Получить объект Course
        course = self.get_object()

        if 'module_id' in self.kwargs:
            # Взять текущий модуль
            context['module'] = course.modules.get(id=self.kwargs['module_id'])
        else:
            # Взять первый модуль
            context['module'] = course.modules.all()[0]

        return context


if __name__ == '__main__':
    # Интроспекция класса UpdateView
    from django.views.generic import UpdateView

    methods_of_update_view = list(method for method in dir(UpdateView) if not method.startswith('__'))
    for method_name in methods_of_update_view:
        method = getattr(UpdateView, method_name)  # Получить объект метода
        docstring = method.__doc__  # Получить документацию метода
        if docstring:
            print(f"Method: {method_name}\nDocumentation: {docstring}\n")

app/account/templates/profile/profile_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="profile-wrapper">
    <h5 class="card-title">{{ profile }}</h5>
    <div class="card-text">
        <div class="profile-info">
            {% if profile.avatar %}
                <img src="{{ profile.avatar.url }}" alt="Аватар: {{ profile.user.username }}" class="profile-avatar">
            {% else %}
                <img src="{% static 'img/profile_avatars/default_profile_avatar.jpg' %}" alt="Дефолтный аватар" class="profile-avatar">
            {% endif %}
            <ul class="profile-details">
                <li><span class="detail-label">Никнейм:</span> {{ profile.user.username }}</li>
                {% if profile.user.get_full_name %} <li><span class="detail-label">Имя и фамилия:</span> {{ profile.user.get_full_name }}</li> {% endif %}
                <li><span class="detail-label">Заходил:</span> {{ profile.user.last_login }}</li>
                <li><span class="detail-label">Дата рождения:</span> {{ profile.birth_date }}</li>
                <li><span class="detail-label">О себе:</span> {{ profile.bio }}</li>
            </ul>
        </div>
        {% if request.user == profile.user %}
            <div class="profile-actions">
                <a href="{% url 'account:profile_edit' slug=profile.slug %}" class="edit-profile-link">Редактировать профиль</a>
                <a href="{% url 'password_change' %}" class="change-password-link">Изменить пароль</a>
            </div>
        {% endif %}
    </div>
</div>
{% endblock %}

app/account/templates/profile/profile_edit.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    {% comment %} <div class="profile-edit__wrapper">
        <h3 class="profile-edit__wrapper__card-title">ИЗМЕНИТЬ {{ profile|upper }}</h1>
        <div class="profile-edit__wrapper__card-text">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ user_form.as_div }}
                {{ form.as_div }}
                <p><input type="submit" value="Сохранить изменения"></p>
            </form>
        </div>
    </div> {% endcomment %}

    <div class="profile-wrapper">
        <h3 class="profile-wrapper__card-title">ИЗМЕНИТЬ ПРОФИЛЬ ПОЛЬЗОВАТЕЛЯ: DELLREAM</h3>
        
        <div class="card-text">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
    
                <!-- User Form Fields -->
                <div class="form-group">
                    <label for="{{ user_form.first_name.id_for_label }}">Имя:</label>
                    {{ user_form.first_name }}
                </div>
    
                <div class="form-group">
                    <label for="{{ user_form.last_name.id_for_label }}">Фамилия:</label>
                    {{ user_form.last_name }}
                </div>
    
                <div class="form-group">
                    <label for="{{ user_form.email.id_for_label }}">Электронная почта:</label>
                    {{ user_form.email }}
                </div>
    
                <!-- Profile Form Fields -->
                <div class="form-group">
                    <label for="{{ form.birth_date.id_for_label }}">Дата рождения:</label>
                    {{ form.birth_date }}
                </div>
    
                <div class="form-group-avatar">
                    <label for="{{ form.avatar.id_for_label }}">Фотография:</label>
                    {{ form.avatar }}
                    {% if profile.avatar %}
                        <img src="{{ profile.avatar.url }}" alt="Аватар: {{ profile.user.username }}" class="profile-avatar">
                    {% else %}
                        <img src="{% static 'img/profile_avatars/default_profile_avatar.jpg' %}" alt="Дефолтный аватар" class="profile-avatar">
                    {% endif %}

                    <div class="form-group-avatar__delete">
                        <label for="{{ form.delete_avatar.id_for_label }}">Удалить текущую фотографию:</label>
                        {{ form.delete_avatar }}
                    </div>

                </div>
    
                <div class="form-group">
                    <label for="{{ form.bio.id_for_label }}">Информация о себе:</label>
                    {{ form.bio }}
                </div>
    
                <div class="form-group">
                    <label for="{{ form.slug.id_for_label }}">Ссылка на профиль:</label>
                    {{ form.slug }}
                </div>
    
                <div class="form-group">
                    <input type="submit" value="Сохранить изменения">
                </div>
            
            </form>
        
        </div>
            
    </div>
    
    
    
{% endblock %}